stages:
  - test
  - deploy

test:
  image: docker:18-git
  stage: test
  services:
    - docker:18-dind
  script:
    - docker build -t palange .
    - docker run palange "coverage run manage.py test; coverage report"
  before_script:
    - apk add --no-cache docker-compose
  coverage: '/TOTAL\s+\d+\s+\d+\s+(\d+%)/'
  after_script:
    - docker rmi palange


deploy:
  image: gitlab/dind:latest
  stage: deploy
  when: manual
  environment:
    name: arvan
  only:
    - master
  script:
    - 'which ssh-agent || ( apt-get install -qq openssh-client )'
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - ssh ubuntu@${ARVAN_HOST} "cd palange && git checkout master && git pull origin master && exit"