# Generated by Django 3.0.4 on 2020-06-12 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0002_organizerprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizerprofile',
            name='score',
            field=models.IntegerField(),
        ),
    ]
