# Generated by Django 3.0.4 on 2020-07-16 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0004_auto_20200612_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favorite_tags',
            field=models.CharField(default='', max_length=2000, verbose_name='Favorite Tags'),
            preserve_default=False,
        ),
    ]
