# Generated by Django 3.0.4 on 2020-07-31 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0005_profile_favorite_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='god',
            field=models.BooleanField(default=False),
        ),
    ]
