# Generated by Django 3.0.4 on 2020-04-14 19:04

from django.db import migrations, models
import django.db.models.deletion
import trips.models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=trips.models.image_upload_name)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trips.Trip', verbose_name='Trip')),
            ],
        ),
    ]
