# Generated by Django 3.0.4 on 2020-04-23 07:17

from django.db import migrations, models
import trips.models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_tripimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='image',
            field=models.ImageField(default='', upload_to=trips.models.image_upload_name),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='TripImage',
        ),
    ]
