# Generated by Django 3.0.4 on 2020-06-12 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0003_auto_20200612_1937'),
        ('trips', '0005_auto_20200607_0405'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='tags_raw',
            field=models.TextField(default=[], max_length=4096),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='TripRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField()),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trips.Trip')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user_auth.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='TripFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=4096)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trips.Trip')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user_auth.Profile')),
            ],
        ),
    ]
