# Generated by Django 3.0.4 on 2020-06-12 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0004_auto_20200612_2047'),
        ('trips', '0007_auto_20200612_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='profile',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='user_auth.Profile'),
        ),
    ]
