# Generated by Django 3.0.4 on 2020-06-12 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0008_comment_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='block',
            field=models.BooleanField(default=False),
        ),
    ]
