# Generated by Django 3.0.4 on 2020-07-31 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0005_profile_favorite_tags'),
        ('trips', '0010_ads'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='seen',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ads',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user_auth.Profile'),
        ),
    ]
